Repository CVO-Org/immersion-cigs-rewrite, pull requests merged in 2025-07, with the labels that each got.

#83 Translation French
  addons/core/stringtable.xml
Labels: changelog/translation

#70 Support: ACE Advanced Fatigue
  .hemtt/launch.toml
  .hemtt/missions/test.VR/mission.sqm
  .hemtt/project.toml
  addons/core/CfgFunctions.hpp
  addons/core/CfgSounds.hpp
  addons/core/XEH/cba_settings_common.inc.sqf
  addons/core/data/sounds/cough_0.ogg
  addons/core/data/sounds/cough_1.ogg
  addons/core/data/sounds/cough_2.ogg
  addons/core/functions/adv_fatigue/fn_adv_fatigue_addPuffs.sqf
  addons/core/functions/adv_fatigue/fn_adv_fatigue_dutyFactor.sqf
  addons/core/functions/adv_fatigue/fn_adv_fatigue_enable.sqf
  addons/core/functions/combustion/fn_combustion_do.sqf
  addons/core/functions/combustion/fn_combustion_init.sqf
  addons/core/functions/eat_cig/fn_addEatAction.sqf
  addons/core/functions/effects/fn_cough.sqf
  addons/core/functions/effects/fn_sound.sqf
  addons/core/functions/fn_postInit.sqf
  addons/core/functions/lighter/fn_useLighter.sqf
  addons/core/functions/pack/fn_take_from_pack.sqf
  addons/core/functions/smoking/fn_smoking.sqf
  addons/core/functions/smoking/fn_start_cig_their.sqf
  addons/core/functions/smoking/fn_start_cig_your.sqf
  addons/core/functions/smoking/fn_start_smoking.sqf
  addons/core/functions/smoking/fn_stop_cig.sqf
  addons/core/functions/sucking/fn_start_sucking.sqf
  addons/core/functions/sucking/fn_sucking.sqf
  addons/core/stringtable.xml
  addons/main/script_macros_zrn.hpp
  addons/main/script_version.hpp
  addons/morley/defines.hpp
Labels: changelog/enhancement

#92 CBA Settings: Improved handling for coughing and combustion modifier
  addons/core/XEH/cba_settings_common.inc.sqf
  addons/core/functions/adv_fatigue/fn_adv_fatigue_addPuffs.sqf
  addons/core/functions/combustion/fn_combustion_check.sqf
  addons/core/functions/combustion/fn_combustion_init.sqf
  addons/core/stringtable.xml
Labels: changelog/improvement

#93 Update README.md
  README.md
Labels: changelog/ignore
